version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - revive
    - unused
    - whitespace
  settings:
    revive:
      severity: warning
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
