const config = {
  // basename: only at build time to set, and Don't add '/' at end off BASENAME for breadcrumbs, also Don't put only '/' use blank('') instead,
  // like '/berry-material-react/react/default'
  basename: '/',
  defaultPath: '/panel/dashboard',
  fontFamily: `'Roboto', Helvetica, sans-serif`,
  borderRadius: 12,
  siteInfo: {
    UptimeEnabled: false,
    UptimeDomain: '',
    UptimePageName: '',
    UserInvoiceMonth: false,
    builtin_chat_enabled: true,
    chat_link: '',
    display_in_currency: true,
    docs_link: '',
    email_verification: false,
    footer_html: '',
    analytics_code: '',
    github_client_id: '',
    github_oauth: false,
    linuxDo_client_id: '',
    linuxDo_oauth: false,
    oidc_auth: false,
    oidc_display_name: '',
    oidc_providers: [],
    password_login: true,
    password_register: true,
    oidc_auto_redirect: false,
    logo: '',
    quota_per_unit: 500000,
    server_address: '',
    start_time: 0,
    system_name: 'Modeltaps',
    language: 'zh_CN',
    top_up_link: '',
    turnstile_check: false,
    turnstile_site_key: '',
    version: '',
    wechat_login: false,
    wechat_qrcode: '',
    lark_login: false,
    lark_client_id: '',
    telegram_bot: '',
    max_log_query_days: 366,
    max_log_lookback_days: 731,
    isLoading: true // 添加加载状态
  }
};

export default config;
